name: sig

on: [push, pull_request]

jobs:
  sig:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - name: Install dependencies
        run: |
          bundle config set with 'sig'
          bundle install
      - name: Run RBS test
        run: bundle exec rake rbs:test
